feat: Example using sub-commands
Add target `lib.%:`

TODO: We need to indent the list.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -10,8 +10,12 @@ help h H:     ## Show this help message
 	@echo "Targets:"
 	@awk -f support/target-list.awk $(lastword $(MAKEFILE_LIST))
 
+lib.%:   ## `make lib.<cmd> PKG=<pkg>` -> `arduino-cli lib <cmd> "$(PKG)"`. For lib help `make lib.help`. Example: `make lib.install PKG="ArduinoJson"`
+	@[ -n "$*" ] && arduino-cli lib "$*" "$(PKG)" \
+	 || { echo "Error: missing cmd in lib.<cmd>" >&2; exit 1; }
+
 compile c:    ## Build the project from source
-	echo "Translate source files to object files."
+	@echo "Translate source files to object files."
 
 clean:        ## Remove build artifacts
-	echo "Remove any and all build artifacts."
+	@echo "Remove any and all build artifacts."
